### ISSUE TITLE
Complete Eclipse Foundation Code checklist

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/lsp4jakarta#333]
Ensure that all the code requirements are met per the Eclipse projects handbook checklist (https://www.eclipse.org/projects/handbook/#checklist)

All project code is managed in source code repositories provided by The Eclipse Foundation;
- [ ] Naming conventions followed: 
- e.g. org.eclipse.<shortname>.<component>[.*] for Java packages and OSGi Bundles;

- [ ] Provider information is set to the project’s formal name:
- e.g. the Bundle-Vendor entry set to "Eclipse Foo" in OSGi Bundles; or
- e.g. the project and organization names are set to "Eclipse Foo" in Maven pom.xml files;

- [ ] [Legal documentation](https://www.eclipse.org/projects/handbook/#legaldoc) is provided:
- All source files include a copyright and license header (when technically feasible);
- All source code repositories include a [LICENSE](https://www.eclipse.org/projects/handbook/#legaldoc-license) file (or equivalent) in the root; and
- All source code repositories include a [NOTICES](https://www.eclipse.org/projects/handbook/#legaldoc-notice) file (or—​for projects that produce Eclipse Platform plug-ins--about.html files as described by the [Legal Documentation for Eclipse Platform Plug-ins and Fragments](https://www.eclipse.org/projects/handbook/#legaldoc-plugins));

- [ ] All source code repositories include a [CONTRIBUTING](https://www.eclipse.org/projects/handbook/#legaldoc-contributor) file (or equivalent) in the root; and

- [ ] All feature names and descriptions are captured, are spelled correctly, use proper grammar, and contain content that is actually useful for the intended audience.

**Comment by TrevCraw** [comment]
Updates should be made for incubation labelling: https://www.eclipse.org/projects/handbook/#starting-incubation-branding
If possible, add incubation image to release page: I'm thinking we should add the incubation logo to the release page if possible https://github.com/eclipse/lsp4jakarta/releases

**Comment by kathrynkodama** [comment]
For the first bullet above "Naming conventions", there are still some packages in the `jakarta.eclipse` component that should be updated to `org.eclipse.LSP4Jakarta`. https://github.com/eclipse/lsp4jakarta/tree/main/jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core

Confirmed that the `jakarta.jdt` and `jakarta.ls` components both have the correct package names.

With https://github.com/eclipse/lsp4jakarta/pull/3 the second bullet "Provider information is set to the project’s formal name" is complete
