### ISSUE TITLE
Support for Jakarta EE 10 Web Profile APIs

### ISSUE THREAD

**Issue by yeekangc** [eclipse/lsp4jakarta#469]
#### Description:
Complete coding assistance for Jakarta EE 10 Web Profile APIs

#### Specification:
Jakarta EE 10 Web Profile

#### Type of language feature proposed:
_Select all that apply_
- [x] diagnostic
- [x] quick-fix
- [x] snippet
- [ ] other, please specify:

**Comment by ajm01** [comment]
https://jakarta.ee/specifications/webprofile/10/

**Items remaining from JakartaLS EE9 Support Epic**

Jakarta Bean Validation 3.0
- [ ] #63
  - [ ] quick fix

Jakarta JSON Binding 2.0

- [ ] https://github.com/eclipse/lsp4jakarta/issues/292
- [ ] https://github.com/eclipse/lsp4jakarta/issues/292

Jakarta Contexts and Dependency Injection 3.0

- [ ] #105 
- [ ] #134 

Jakarta Annotations 2.0

- [ ] #190 
- [ ] #193 

Jakarta Dependency Injection 2.0

- [ ] #162 
- [ ] #163 
- [ ] #164 
- [ ] #192 
- [ ] #211
- [ ] #228 

Jakarta Managed Beans 2.0

- [ ] #162 
- [ ] #163 
- [ ] #192 

Jakarta WebSocket 2.0

- [ ] #244 
- [ ] #249 
- [ ] #282
- [ ] #284 
- [ ] #287 
- [ ] #288 
- [ ] #313
